source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Database handling
#group :sqlite do
#  gem 'sqlite3'
#end
group :mysql do
  gem 'mysql2'
end

gem 'passenger'
gem 'cocaine', '0.2.1'
gem "redcarpet", "2.2.2"
gem "will_paginate", "3.0.5"
gem "rdiscount"
gem "ruby-openid"
gem "rack-openid"
